BloggingAppPlatform.MVC/Controllers/AuthController.cs
using Business.Abstract;
using Entities.DTOs;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace WebApp.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly IUserService _userService;

        public AuthController(IAuthService authService, IUserService userService)
        {
            _authService = authService;
            _userService = userService;
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterDto registerDto)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ErrorMessage = "Please fill out all required fields correctly.";
                return View(registerDto);
            }

            if (registerDto.Password != registerDto.RePassword)
            {
                ViewBag.ErrorMessage = "Passwords do not match.";
                return View(registerDto);
            }

            // Check if email already exists
            var userExistsByMail = _authService.UserExists(registerDto.Email);
            // Check if username already exists
            var userExistsByUsername = _authService.UserExistsByUsername(registerDto.Username);

            // If either email or username exists, display an error message
            if (!userExistsByMail.Success || !userExistsByUsername.Success)
            {
                ViewBag.ErrorMessage = "Email or Username is already used by another user.";
                return View(registerDto);
            }

            // Register the user
            var registerResult = _authService.Register(registerDto, registerDto.Password);
            if (!registerResult.Success)
            {
                ViewBag.ErrorMessage = registerResult.Message;
                return View(registerDto);
            }

            // Generate access token
            var result = _authService.CreateAccessToken(registerResult.Data);
            if (!result.Success)
            {
                ViewBag.ErrorMessage = result.Message;
                return View(registerDto);
            }

            // Redirect to login page upon successful registration
            TempData["SuccessMessage"] = "Registration successful! You can now log in.";
            return RedirectToAction("Login");
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDTO)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ErrorMessage = "Please provide valid credentials.";
                return View(loginDTO);
            }

            var userToLogin = _authService.Login(loginDTO);
            if (!userToLogin.Success)
            {
                ViewBag.ErrorMessage = userToLogin.Message;
                return View(loginDTO);
            }

            var result = _authService.CreateAccessToken(userToLogin.Data);
            if (!result.Success)
            {
                ViewBag.ErrorMessage = result.Message;
                return View(loginDTO);
            }

            var token = result.Data; 

            var tokenHandler = new System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler();
            var jwtToken = tokenHandler.ReadJwtToken(token.Token);

            var expClaim = jwtToken.Claims.FirstOrDefault(c => c.Type == "exp");
            if (expClaim != null)
            {
                var expirationTime = DateTimeOffset.FromUnixTimeSeconds(long.Parse(expClaim.Value));

                Response.Cookies.Append("auth_token", token.Token, new CookieOptions
                {
                    HttpOnly = true, 
                    Secure = true, 
                    SameSite = SameSiteMode.Strict, 
                    Expires = expirationTime 
                });
            }

            // Create claims
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, userToLogin.Data.Username),
                new Claim(ClaimTypes.Email, userToLogin.Data.Email),
                new Claim("userId", userToLogin.Data.Id.ToString()),
            };

            var roles = _userService.GetClaims(userToLogin.Data);
            foreach (var role in roles)
            {
                claims.Add(new Claim(ClaimTypes.Role, role.Name));
            }

            // Create ClaimsIdentity and sign in
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authProperties = new AuthenticationProperties { IsPersistent = true };

            // Sign in user
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            // Log the user out
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            // Remove the auth_token cookie on logout
            Response.Cookies.Delete("auth_token");
            return RedirectToAction("Index", "Home");
        }

    }
}

BloggingAppPlatform.MVC/Controllers/ReportController.cs
using Business.Abstract;
using Entities.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace BloggingAppPlatform.MVC.Controllers
{
    public class ReportController : Controller
    {
        private readonly IReportService _reportService;
        public ReportController(IReportService reportService)
        {
            _reportService = reportService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Report(ReportDto report)
        {
            _reportService.AddReport(report);
            return RedirectToAction("Index", "Home");
        }
    }
}

BloggingAppPlatform.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BloggingAppPlatform.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BloggingAppPlatform.MVC.styles.css" asp-append-version="true" />
    <link href="https://bootswatch.com/5/sketchy/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    @* Render the navigation only if the HideLayoutSections flag is not set *@
    @if (ViewData["HideLayoutSections"] == null || !(bool)ViewData["HideLayoutSections"])
    {
        <nav class="navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark ticky-top bg-body-tertiary" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand fw-light" asp-controller="Home" asp-action="Index">
                    <span class="fas fa-brain me-1"></span> Ideas
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated) // User is not logged in
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="/Auth/Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Auth/Register">Register</a>
                            </li>
                        }
                        else // User is logged in
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Profile" asp-action="Index">Profile</a>
                            </li>
                           
                            @* Button for admin access if user is an admin or moderator *@
                            @if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                                </li>
                            }

                            <li class="nav-item">
                                <form asp-controller="Auth" asp-action="Logout" method="post" class="d-inline">
                                    <button type="submit" class="nav-link btn btn-link text-light">Logout</button>
                                </form>
                            </li>
                        }
                       
                    </ul>
                </div>
            </div>
        </nav>
    }

    <div class="container py-4">
        <div class="row justify-content-center">
            @if (User.Identity.IsAuthenticated)
            {
            <div class="col-3">
                @* Render the sidebar only if the HideLayoutSections flag is not set *@
                @if (ViewData["HideLayoutSections"] == null || !(bool)ViewData["HideLayoutSections"])
                {
                    <div class="card overflow-hidden">
                        <div class="card-body pt-3">
                            <ul class="nav nav-link-secondary flex-column fw-bold gap-2">
                                <li class="nav-item">
                                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">
                                        <span>Home</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                        <a class="nav-link" asp-controller="Report" asp-action="Index">
                                        <span>Report</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                                        <span>Support</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-footer text-center py-2">
                                <a class="btn btn-link btn-sm" asp-controller="Profile" asp-action="Index">View Profile </a>
                        </div>
                    </div>
                }
            </div>
            }
            <div class="col-6 text-center">
                @RenderBody()
            </div>
            @if (User.Identity.IsAuthenticated)
            {
            <div class="col-3">
                @* Render the search and follow sections only if the HideLayoutSections flag is not set *@
                @if (ViewData["HideLayoutSections"] == null || !(bool)ViewData["HideLayoutSections"])
                {
                    <div class="card">
                        <div class="card-header pb-0 border-0">
                            <h5 class="">Search</h5>
                        </div>
                        <div class="card-body">
                             <form method="get" action="/Profile/GetProfile">
                                <input placeholder="..." class="form-control w-100" name="userName" type="text" id="search">
                                <button type="submit" class="btn btn-dark mt-2"> Search</button>
                              </form> 
                        </div>
                    </div>
                    @* <div class="card mt-3">
                        <div class="card-header pb-0 border-0">
                            <h5 class="">Who to follow</h5>
                        </div>
                        <div class="card-body">
                            <!-- Follow suggestions -->
                        </div>
                    </div> *@
                }
            </div>
            }
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous">
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>